### ISSUE TITLE
How to transfer files to LG webos?

### ISSUE THREAD

**Issue by Soloabed** [satgit62/pvr.hts-tvhead-client-on-LG-webOS#3]
I need to transfer pvr.hts-tvhead-client-on-LG-webOS to Kodi on lg webos using FileZilla
is there any other way to transfer these files to TV?

**Comment by satgit62** [comment]
If you have no possibility to transfer the whole folder with FileZilla to the LG, you can do it with webOS Dev Manager. However, you must first create the new folder with the manager and transfer the files individually to the created folder. 
In most cases, the direct ZIP installation from Kodi also works.  Pack the ZIP onto a USB stick and navigate to `/tmp/usb/sda/sda1/` during installation.

webOS Dev Manager
![webOS Dev Manager](https://github.com/user-attachments/assets/3e5f3535-5cdc-4337-a370-57118dc622fb)

**Comment by Soloabed** [comment]
First let me thank you for your reply.  In my webOS Dev Manager(Mac version) I do not have add new directory, I have only upload, download and delete
![Screen Shot 2024-10-21 at 10 34 11 AM](https://github.com/user-attachments/assets/930ed166-82c8-4827-8676-1e8ee5cbdc89)

**Comment by satgit62** [comment]
Then you are using an outdated version that did not yet have the Create Folder function.
Here is the new one for Mac and Windows: https://github.com/webosbrew/dev-manager-desktop/releases/tag/v1.13.3

**Comment by Soloabed** [comment]
I uploaded the files and installed Inputstream FFmpeg Direct. But still IPTV Manager and IPTVsime is not working!

**Comment by satgit62** [comment]
I would need to view their kodi.log from `.kodi/temp/` directory.

**Comment by Soloabed** [comment]
[kodi.log](https://github.com/user-attachments/files/17459339/kodi.log)

**Comment by satgit62** [comment]
Do you have webOS 3.X?  Kodi (21.0 (21.0.0) Git:20240406-60c4500054). Platform: webOS ARM 32-bit
Which build have you installed and From which source?
There are problems with the “inputstream.rtmp”:

The archive 'zip://%2fmedia%2fdeveloper%2ftmp%2finputstream.rtmp.zip/inputstream.rtmp/' could not be unpacked to '/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/temp/72e5eb0a-c3c2-4f32-aa32-4a4cfb7e6fc9'.

**Comment by Soloabed** [comment]
Webos 4.10, I tried Kodi 20.0 the now I have Kodi 21 for Webos LG

**Comment by satgit62** [comment]
Okay, if they use the release version 21 from Homebrew Channel, then it doesn't work, it needs to be compiled for their version. Let's see what we can do.

**Comment by satgit62** [comment]
Can you test this version?

[inputstream.adaptive.zip](https://github.com/user-attachments/files/17459968/inputstream.adaptive.zip)

**Comment by satgit62** [comment]
[inputstream.rtmp.zip](https://github.com/user-attachments/files/17460025/inputstream.rtmp.zip)
[pvr.hts.zip](https://github.com/user-attachments/files/17460027/pvr.hts.zip)

**Comment by Soloabed** [comment]
I tried as a zip file but it fail to install, I will try to transfer the files

**Comment by satgit62** [comment]
> I tried as a zip file but it fail to install, I will try to transfer the files

Hello,
Please let me know who did not work, as I am in the process of compiling the latest version from the homebrew channel to build the binary add-ons accordingly.

**Comment by Soloabed** [comment]
Sure, I will tell you as soon as I finish transferring the files to addons on my TV

**Comment by Soloabed** [comment]
IPTV manger installed but IPTVsimple playback failed after installation of inputstream.adaptive and even after insllation of inputstream.rtmp and pvr.hts

**Comment by satgit62** [comment]
I don't know what they need from it, but there are the new compiled PVRs. The old ones need to be uninstalled.
Try ZIP installation first.
[inputstream.adaptive.zip](https://github.com/user-attachments/files/17463859/inputstream.adaptive.zip)
[inputstream.ffmpegdirect.zip](https://github.com/user-attachments/files/17463860/inputstream.ffmpegdirect.zip)
[inputstream.rtmp.zip](https://github.com/user-attachments/files/17463863/inputstream.rtmp.zip)
[pvr.hts.zip](https://github.com/user-attachments/files/17463865/pvr.hts.zip)
[pvr.iptvsimple.zip](https://github.com/user-attachments/files/17463866/pvr.iptvsimple.zip)
[pvr.stalker.zip](https://github.com/user-attachments/files/17463867/pvr.stalker.zip)

**Comment by Soloabed** [comment]
IPTVsimple playback failed. IPTV Manager installed successfully but this did not help play IPTV.

**Comment by Soloabed** [comment]
the compiled pvr.iptvsimple is incompatable with Kodi 21.0

**Comment by satgit62** [comment]
Hmm, that's crazy, that's compiled with the 21 dependencies. Can the other things be installed? Have you tried it as a ZIP? What message did you get?

**Comment by satgit62** [comment]
I have compiled again, test it 
[pvr.iptvsimple.zip](https://github.com/user-attachments/files/17466735/pvr.iptvsimple.zip)

**Comment by Soloabed** [comment]
all zip files can not be installed. inputstream.adaptive installed

**Comment by Soloabed** [comment]
I tried the recompiled version of pvr.iptvsimple but I got the same result of not compatible to kodi 21.0

**Comment by Soloabed** [comment]
the new log 
[kodi.log](https://github.com/user-attachments/files/17467560/kodi.log)

**Comment by Soloabed** [comment]
This is the info about my TV 
![Screen Shot 2024-10-22 at 1 48 55 AM](https://github.com/user-attachments/assets/54e9dca9-2027-4326-bdf3-16cfa1e3fa45)

**Comment by satgit62** [comment]
Hi,
I had a look at the kodi.log and realized that actually all PVR's are already integrated in the build. You can install directly from PVR repository and not compile extra. See log image.
If the whole thing does not work for you, it is probably due to your K5lp board. It is known that it currently does not work on TVs with a Realtek K5Lp SoC OTAID with W19P.
You need to find out if this applies to your device.
webOS Dev Manager v1.12.2 or later should be able to show your OTAID, at least on webOS 4.0+.

![PVR](https://github.com/user-attachments/assets/543e517d-10aa-476b-ac11-fb52ae209d05)

**Comment by Soloabed** [comment]
Thank you for your efforts.
